name: test2

on:
  workflow_run:
    worksflows: ["test1"]
    types:
      - completed

jobs:
  test1:
    runs-on: ubuntu-latest
    steps:
      - name: test2
        run: |
          echo "bye..."